project:
  type: website
  output-dir: docs
  
website:
  title: "Data Visualization Essentials"
  navbar:
    left:
    - text: ""
      href: index.qmd
      icon: fa-home
    - text: Slides and Resources
      href: background.qmd
    - text: Exploring Plot Types
      href: plots.qmd
    - text: Discussing Common Challenges
      href: discussion.qmd
    - text: Activity
      href: activity.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
