---
title: "**Resources**"
output:
  html_document
---

# Slides

Slides for workshop: [https://docs.google.com/presentation/d/1wSy8jDOnuETR5Y9jbK6m5eNbQsxSWnyYio-wPs-m3YE/edit?usp=sharing](https://docs.google.com/presentation/d/1wSy8jDOnuETR5Y9jbK6m5eNbQsxSWnyYio-wPs-m3YE/edit?usp=sharing)

* Background and Fundamentals: Slides `12` - `64`
* Exploring Plot Types: Slides `66` - `76`
* Best Practices for Ethical and Accessible Data Visualizations: Slides `78` - `144`
* Discussion: Common Data Visualization Challenges: Slides `146` - `171`
* Activity: Building an Expository Graph: Slides `172` - `183`


# Pre-requisites and needs

Throughout the workshop, participants will want to have **access to a web browser** to interact with polls / survey questions on [slido.com](https://www.slido.com/).

For the Exploring Plot Types section, participants will want to have access to a web browser to interact with the Google Docs and Google Slides deck. No Google account login required.

For the Building an Expository Graph section, participants will want to have **downloaded the data** and have **access to R and RStudio** (or an equivalent integrated development environment for R).


# Other Resources

* ITN Considerations for Data Visualization Course: [https://hutchdatascience.org/DataViz_Considerations/](https://hutchdatascience.org/DataViz_Considerations/)
* Tidyverse Skills for Data Science Course: [Visualizing Data in the Tidyverse chapter](https://jhudatascience.org/tidyversecourse/dataviz.html#about-this-course-3)
* NCI Data Visualization Basics: [https://datascience.cancer.gov/training/learn-data-science/visualize-data-basics](https://datascience.cancer.gov/training/learn-data-science/visualize-data-basics)
* Exploratory vs Expository Graphs: [https://jtleek.com/ads2020/week-10.html#creating-expository-graphs](https://jtleek.com/ads2020/week-10.html#creating-expository-graphs)
* [Data Visualization: A Practical Introduction by Kieran Healy](https://socviz.co/)
* The Visual Display of Quantitative Information by Edward R. Tufte (book)
* [Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures by Claus O. Wilke](https://clauswilke.com/dataviz/)
* [10 Simple Rules for Better Figures](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)
* Gallery for common plots: [https://www.data-to-viz.com/#explore](https://www.data-to-viz.com/#explore)
* [Python Graph Gallery](https://python-graph-gallery.com/)
* [R Graph Gallery](https://r-graph-gallery.com/)
* Genomics Data Visualization Course Gallery from Dr. Fan's JHU course: [https://jef.works/genomic-data-visualization-2024/](https://jef.works/genomic-data-visualization-2024/)
* [Urban Institute Do No Harm Guides](https://www.urban.org/projects/do-no-harm-project)
  * [Accessibility Guide](https://www.urban.org/research/publication/do-no-harm-guide-centering-accessibility-data-visualization)
  * [Empathy Guide](https://www.urban.org/research/publication/do-no-harm-guide-applying-equity-awareness-data-visualization)
