---
title: "**DeCoDE Institute Summer 2026: Data Visualization Essentials**"
output:
  html_document
---

### **About**

This workshop introduces key considerations for creating effective data visualizations, including how to choose appropriate plots and communicate insights clearly. Participants will learn core design principles, accessibility practices, and strategies to avoid misleading or distorted visuals. Through examples attendees will develop skills to evaluate and create clear, informative, and publication-ready figures.

#### **Outline** 

We will

* Discuss Background and Fundamentals
  * What is Data Visualization?
  * Why is Data Visualization Important?
  * What are Common Uses for Data Visualization?
  * Types of Data and Research Questions
* Discuss and Explore Plot types
  * Building Blocks for Data Visualization
  * Useufl Visual Design Principles
  * Exploring Common Plot Types
    *  Basic and field specific
    *  When is a specific plot type the most appropriate to use?
    *  Description and example(s)
* Discuss Ethical and Accessible Data Visualization
  * Best Practices
  * Improving Visualizations
* Discuss Common Challenges
* Build an Expository Graph (activity)

### **Slides**

[Access to Slides for Workshop](https://docs.google.com/presentation/d/1wSy8jDOnuETR5Y9jbK6m5eNbQsxSWnyYio-wPs-m3YE/edit?usp=sharing)

### **Pre-requisites and need**

Throughout the workshop, participants will want to have **access to a web browser** to interact with polls / survey questions on [slido.com](https://www.slido.com/). 

For the Exploring Plot Types section, participants will want to have access to a web browser to interact with the Google Docs and Google Slides deck. No Google account login required.

For the Building an Expository Graph section, participants will want to have **downloaded the data** and have **access to R and RStudio** (or an equivalent integrated development environment for R).

